package com.brillio.dhi.dao.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "FILE_UPLOAD_DATA_SOURCE")
public class FileUploadDataSource implements java.io.Serializable {

	private Long dataModelRowId;
	private UserProfileEntity userProfile;
	private String dataModelFileName;
	//private String mappedDataModelFileName;
	private String aliasFileName;
	private String isActive;
	private String defaultFlag;
	private Date createdDate;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getDataModelRowId() {
		return dataModelRowId;
	}
	public void setDataModelRowId(Long dataModelRowId) {
		this.dataModelRowId = dataModelRowId;
	}
	
	@OneToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "USER_PROFILE")
	public UserProfileEntity getUserProfile() {
		return userProfile;
	}
	public void setUserProfile(UserProfileEntity userProfile) {
		this.userProfile = userProfile;
	}
	
	@Column(name = "DATA_MODEL_FILE_NAME", nullable = false)
	public String getDataModelFileName() {
		return dataModelFileName;
	}
	public void setDataModelFileName(String dataModelFileName) {
		this.dataModelFileName = dataModelFileName;
	}
	
	@Column(name = "ALIAS_FILE_NAME", nullable = false)
	public String getAliasFileName() {
		return aliasFileName;
	}
	public void setAliasFileName(String aliasFileName) {
		this.aliasFileName = aliasFileName;
	}
	
	@Column(name = "IS_ACTIVE", nullable = false)
	public String getIsActive() {
		return isActive;
	}
	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}
	
	
	@Column(name = "DEFAULT_FLAG", nullable = false)
	public String getDefaultFlag() {
		return defaultFlag;
	}
	public void setDefaultFlag(String defaultFlag) {
		this.defaultFlag = defaultFlag;
	}
	
	
	@Column(name = "CREATED_DATE", nullable = false)
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
}
