package com.brillio.dhi.dao.entity;

// Generated Mar 11, 2017 11:20:18 PM by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "user_profile", uniqueConstraints = @UniqueConstraint(columnNames = "phone_number"))
public class UserProfileEntity implements java.io.Serializable {

	private String username;
	private String firstname;
	private String middlename;
	private String lastname;
	private String phoneNumber;
	private Date profileCreatedDate;
	private Date profileModifiedDate;

	public UserProfileEntity() {
	}

	public UserProfileEntity(String username, String firstname, String lastname,
			Date profileCreatedDate, Date profileModifiedDate) {
		this.username = username;
		this.firstname = firstname;
		this.lastname = lastname;
		this.profileCreatedDate = profileCreatedDate;
		this.profileModifiedDate = profileModifiedDate;
	}

	public UserProfileEntity(String username, String firstname, String middlename,
			String lastname, String phoneNumber, Date profileCreatedDate,
			Date profileModifiedDate) {
		this.username = username;
		this.firstname = firstname;
		this.middlename = middlename;
		this.lastname = lastname;
		this.phoneNumber = phoneNumber;
		this.profileCreatedDate = profileCreatedDate;
		this.profileModifiedDate = profileModifiedDate;
		
	}

	@Id
	@Column(name = "username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "firstname", nullable = false)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "middlename")
	public String getMiddlename() {
		return this.middlename;
	}

	public void setMiddlename(String middlename) {
		this.middlename = middlename;
	}

	@Column(name = "lastname", nullable = false)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phone_number", unique = true, length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "profile_created_date", nullable = false, length = 19)
	public Date getProfileCreatedDate() {
		return this.profileCreatedDate;
	}

	public void setProfileCreatedDate(Date profileCreatedDate) {
		this.profileCreatedDate = profileCreatedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "profile_modified_date", nullable = false, length = 19)
	public Date getProfileModifiedDate() {
		return this.profileModifiedDate;
	}

	public void setProfileModifiedDate(Date profileModifiedDate) {
		this.profileModifiedDate = profileModifiedDate;
	}

	

}
