package com.brillio.dhi.dao.entity;

// Generated Mar 11, 2017 11:20:18 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UserAuth generated by hbm2java
 */
@Entity
@Table(name = "user_auth", uniqueConstraints = @UniqueConstraint(columnNames = "phone_number"))
public class UserAuth implements java.io.Serializable {

	private String username;
	private String password;
	private Date passwordModifiedDate;
	private String isActive;
	private String phoneNumber;

	public UserAuth() {
	}

	public UserAuth(String username, String password,
			Date passwordModifiedDate, String isActive) {
		this.username = username;
		this.password = password;
		this.passwordModifiedDate = passwordModifiedDate;
		this.isActive = isActive;
	}

	public UserAuth(String username, String password,
			Date passwordModifiedDate, String isActive, String phoneNumber) {
		this.username = username;
		this.password = password;
		this.passwordModifiedDate = passwordModifiedDate;
		this.isActive = isActive;
		this.phoneNumber = phoneNumber;
	}

	@Id
	@Column(name = "username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "password_modified_date", nullable = false, length = 19)
	public Date getPasswordModifiedDate() {
		return this.passwordModifiedDate;
	}

	public void setPasswordModifiedDate(Date passwordModifiedDate) {
		this.passwordModifiedDate = passwordModifiedDate;
	}

	@Column(name = "isActive", nullable = false, length = 5)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@Column(name = "phone_number", unique = true, length = 15)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

}
