package com.brillio.dhi.dao.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "USER_DEFINED_COLUMNS")
public class UserDefinedColumns implements java.io.Serializable {

	private Long userDefinedColumRowId;
	private UserProfileEntity userProfile;
	private String dataColumnName;
	private String aiGeneratedName;
	private String userDefinedName;
	private String description;
	private String dataType;
	private Date createdDate;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getUserDefinedColumRowId() {
		return userDefinedColumRowId;
	}

	public void setUserDefinedColumRowId(Long userDefinedColumRowId) {
		this.userDefinedColumRowId = userDefinedColumRowId;
	}

	
	@OneToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "USER_PROFILE")
	public UserProfileEntity getUserProfile() {
		return userProfile;
	}
	
	public void setUserProfile(UserProfileEntity userProfile) {
		this.userProfile = userProfile;
	}

	@Column(name = "DATA_COLUMN_NAME", nullable = false)
	public String getDataColumnName() {
		return dataColumnName;
	}

	public void setDataColumnName(String dataColumnName) {
		this.dataColumnName = dataColumnName;
	}

	@Column(name = "AI_GENERATED_NAME")
	public String getAiGeneratedName() {
		return aiGeneratedName;
	}

	public void setAiGeneratedName(String aiGeneratedName) {
		this.aiGeneratedName = aiGeneratedName;
	}

	@Column(name = "USER_DEFINED_NAME")
	public String getUserDefinedName() {
		return userDefinedName;
	}

	public void setUserDefinedName(String userDefinedName) {
		this.userDefinedName = userDefinedName;
	}

	@Column(name = "CREATED_DATE")
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	@Column(name = "DESCRIPTION")
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "DATA_TYPE")
	public String getDataType() {
		return dataType;
	}

	public void setDataType(String dataType) {
		this.dataType = dataType;
	}
	
	
}
