package com.brillio.dhi.dao.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * UserProfile generated by hbm2java
 */
@Entity
@Table(name = "USER_QUERY")
public class UserQuery implements java.io.Serializable {

	private Long userQueryRowId;
	private UserProfileEntity userProfile;
	private String query;
	private long count;
	private String channel;
	private Date createdDate;
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	public Long getUserQueryRowId() {
		return userQueryRowId;
	}
	public void setUserQueryRowId(Long userQueryRowId) {
		this.userQueryRowId = userQueryRowId;
	}
	
	@OneToOne(fetch=FetchType.EAGER)
	@JoinColumn(name = "USER_PROFILE")
	public UserProfileEntity getUserProfile() {
		return userProfile;
	}
	
	public void setUserProfile(UserProfileEntity userProfile) {
		this.userProfile = userProfile;
	}
	
	@Column(name = "QUERY", nullable = false)
	public String getQuery() {
		return query;
	}
	public void setQuery(String query) {
		this.query = query;
	}
	
	@Column(name = "COUNT", nullable = false)
	public long getCount() {
		return count;
	}
	public void setCount(long count) {
		this.count = count;
	}
	
	@Column(name = "CREATED_DATE", nullable = false)
	public Date getCreatedDate() {
		return createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}
	
	@Column(name = "CHANNEL", nullable = false)
	public String getChannel() {
		return channel;
	}
	public void setChannel(String channel) {
		this.channel = channel;
	}
	
	
	
}
